# Generated by Django 3.1.5 on 2021-01-24 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='rut')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='cvitae/%d/%m/%Y')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'Trabajador',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
