# Generated by Django 3.1.5 on 2021-01-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210124_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%d/%m/%Y'),
        ),
    ]
